[package]
name = "text"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
im = "15.1.0"
directories = "5.0.1"
anyhow = "1.0.93"
crossterm = "0.28.1"
